name: Automated push to DockerHub

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Running NPM Install
      run: npm ci
    - name: Running NPM build
      run: npm run build --if-present
    - name: Running the unit test
      run: npm test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
      ## In settings/secrets create a 'DOCKERHUB_USERNAME' secrete with your DockerHub username, and a token from DockerHub  
      ## AccountSetting/Security, create a Token with at least write, and save the token to 'DOCKERHUB_TOKEN' in github secrete
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        ## instead of ronberg/test writete first the username and then the repositories name
        ## name/repositories:version
        tags: dm885/microservice-template:latest
